version: "3"

services:
server:
    build: .
    container_name: apisolid
    ports:
      - 3333:3333
    links:
      - database
    api-solid-pg:
      image: bitnami/postgresql
      ports:
        - 5432:5432
      environment:
        DB_USER: postgres
        DB_PWD: postgres
        DB_HOST: apisolid
        DB_PORT: 5432
database:
    image: postgres:13.7
    container_name: database
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=apisolid"
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:


  